name: Continuous Deployment

on:
  push:	
    branches:	
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Node
      uses: actions/setup-node@v1
    - name: Install packages
      run: npm install
    - name: Build
      run: npm run build
    - name: Upload Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: site
        path: dist
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Download Artifacts
        uses: actions/download-artifact@v1
        with:
          name: site
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.1.1
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: 'site'
          CLEAN: true
      
    
